# -----------------------------------------------------------------------------------------------------------
#
# RANDOMLOOTBOXES - Made by Harry8668
#
# ADMIN COMMANDS:
# /alootboxes create [lootbox name] - Creates lootbox :)
# /alootboxes remove [lootbox name] - removes lootbox :)
# /alootboxes addreward [lootbox name] [itemID] - adds reward to lootbox with odds :)
# /alootboxes removereward [lootbox name] [itemID] - removes item from lootbox :)
# /alootboxes give [player] [lootbox name] [amount]
#
# HELP:
# use the config below to edit lootboxes.
# here you can remove/add them along with items and odds to make them
# to your liking. Enjoy! - Harry8668
#
# -----------------------------------------------------------------------------------------------------------

messages:
  prefix: "&f[&b&lELYTRA&f] "
  addedLootbox: "You have added a %lootbox% lootbox!"
  removedLootbox: "You have removed %lootbox%"

lootbox:
